name: Daily RSS Update

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-rss:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run RSS updater
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python "import feedparser.py"
    
    - name: Deploy to server
      # Add your deployment steps here
      # Could be FTP, rsync, or API call to your server
      run: echo "Deploy news_digest.html to your server"
